spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://user-service-db:5432/user_db
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
  autoconfigure:
    exclude:
      - org.springdoc.core.configuration.SpringDocHateoasConfiguration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: 8081

logging:
  level:
    org.hwmoodle: DEBUG
    org.springframework.web: INFO
    org.springframework.data: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

app:
  notification:
    topic: user-events

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      notificationServiceCB:
        register-health-indicator: true
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3
        slow-call-rate-threshold: 100
        slow-call-duration-threshold: 2000
  timelimiter:
    instances:
      notificationServiceCB:
        cancel-running-future: true
        timeout-duration: 5000

